### ISSUE TITLE
クリア画面を作る

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#11]
クリアしたら、トレジャーボックスがあり、スコアが出る。スコアに応じてメッセージとBGMがでる。

**Comment by yanoty3d** [comment]
現状では、正解・間違いを表示させた後にクリア演出になるので、「せいかい」などのテキストが残ってしまう。ここを修正すること。

**Comment by oitsmalab** [comment]
クリア画面で「せいかい」と「ざんねん」の表示を制御した。
@19fa8aa

**Comment by oitsmalab** [comment]
クリア画面でunityちゃんがジャンプした後にスコアが画面の中央に表示される。
@19fa8aa
