### ISSUE TITLE
クイズコースタープレイ中のセンサー値の時間経過の記録

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#14]
クイズコースタープレイ中のセンサー値の時間経過をとる。
- [x] Unityでセンサーを連続的記録する
- [x] 記録した値を、CSVなどで出力する
- [x] CSVをエクセルで読んでみる

**Comment by oitsmalab** [comment]
@84d2a68
gyrocatchのスクリプトのlogSaveでcsvファイルを作成し、書き込むことができた。
しかし、ファイルに追加していくので、アプリを起動したらファイルの中身を削除するか新しいファイルを作成して追加していく様にする。

**Comment by oitsmalab** [comment]
@84d2a68749
アプリを起動させる度に1行下げて、csvファイルにセンサーの値を書き込むことができた。ファイルの書き込みは0.2秒毎にした。

**Comment by oitsmalab** [comment]
csvファイルをエクセルに読み込ませた。
