### ISSUE TITLE
画面の回転方向の有無、数ごとのセンサー値の取得

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#15]
Durovis SDKで動くクイズコースターで、画面が動かない場合、視点によって動く場合において、センサーのログをとる

少なくとも3回は繰り返す
- [x] Durovis SDKで動くクイズコースター
- [ ] 画面が動かない場合のログ
- [ ] 横方向だけの場合のログ
- [ ] 縦横方向の場合のログ
- [ ] 全方向の場合のログ
- [ ] 類似研究の調査

**Comment by oitsmalab** [comment]
DurovisSDKで動くクイズコースターが完了。
Unityちゃんの肌が白いのが気になる。
光源を変えても変わらなかった。
@950c378
