### ISSUE TITLE
DurovisのSDKを用いて、カメラを操作する

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#16]
Durovis SDKをもちい、センサーによって全方向にカメラが移動するようにする
ビルドしないと動かないので、Macで作業したほうが良い

http://qiita.com/warapuri/items/da59cac31feba06a837e

http://warapuri.tumblr.com/post/98800390873/spherical-image-cam%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6unity%E3%81%A7%E5%85%A8%E5%A4%A9%E3%83%91%E3%83%8E%E3%83%A9%E3%83%9E%E5%8B%95%E7%94%BB%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86

**Comment by oitsmalab** [comment]
@9a111de
頭を動かすことでカメラが追従するようになった。
Unityの方でカメラをUnityちゃんの方に向けていたが、Buildしてアプリを起動させるとUnityちゃんの方に向いていなかった。
