### ISSUE TITLE
iPodビルド時のセンサーの出力値の検証

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#18]
- [ ] ｘ、ｙ、ｚ軸に垂直な方向で静置した時の値。
- [ ] ｘ、ｙ、ｚ軸を中心に回転させた時の値

**Comment by oitsmalab** [comment]
accelerationを使うと
x軸に垂直の場合 x≒-9.8 y≒0 z≒0
y軸に垂直の場合 x≒0 y≒-9.7 z≒0
z軸に垂直の場合 x≒0 y≒0 z≒ -9.7
軸の参考　http://internetcom.jp/developer/20100803/26.html

**Comment by oitsmalab** [comment]
accelerationを使うと
x、y、z軸を中心に回転した場合、どの値もほとんど変わらなかった。
