### ISSUE TITLE
ビルド時のセンサー値のログを出力する

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#19]
以下のどちらかの方法
- [ ] iPodローカルに保存して、USB経由でファイルを取得する
- [ ] Niftyクラウドに保存して、サーバーからファイルをダウンロードする

**Comment by oitsmalab** [comment]
ipodのアプリ内のdocument内にセンサーの値を保存することができた。ipodのアプリ内のdocumentはIExplorerを使うことでファイルを取得することができる。
@6d81db4
