### ISSUE TITLE
マーカーからレイを飛ばして、選択肢を選ぶ

### ISSUE THREAD

**Issue by yanoty3d** [smalab/QuizCoaster#22]
カメラからマーカーへレイをRaycastし、マーカーに重なったオブジェクトを認識するようにする。

**Comment by oitsmalab** [comment]
マーカーからレイを飛ばすことで選択しを選べるようにした。
ゴールしてから家の絵を選択することで最初の画面に戻るようにした。
@7b8676c
@74e5b4a
